---
title: '#SLICED as a Forcing Function'
author: Jesse Mostipak
date: '2021-06-04'
slug: []
categories:
  - learning
  - reflection
tags:
  - sliced
  - machine learning
  - tidymodels
  - learnML
subtitle: 'Sometimes the best way to do something is to simply sit down and do it.'
excerpt: 'How choosing to participate in SLICED helped me get serious about learning machine learning.'
images: ~
series: ~
layout: single
---
## Don't let scope creep into your ideas

I am the absolute _master_ at allowing a simple idea [scope creep](https://www.wrike.com/project-management-guide/faq/what-is-scope-creep-in-project-management/) its way into a wholly overwhelming and impossible endeavor. 
More than one "oh this would make a lovely blog post!" idea has turned into "...and then we pitch the idea to VCs and build our own company!" with nothing more than a little time to think and ruminate on how to make _this_ project absolutely perfect.  

I love when things seem perfect, while also recognizing that nothing can ever actually be perfect.
The illusion that perfection is out there and within reach if only I work _hard_ enough and _smart_ enough and get my absolute darling of an idea in front of the right people at the right time is an easy rabbit hole for me to fall down.
In fact I've been living in that rabbit hole for the last five or so years.

## Learning Machine Learning, but for real this time

When I started at Kaggle back in February 2020, it was with the understanding that I would take the time needed to learn both Python and machine learning. 
But shortly after starting, my focus turned primarily to Tensor Processing Units (TPUs) and deep learning with TensorFlow. 
I _tried_ to pick up as much Python and machine learning as I could, taking the Kaggle Learn courses, posting small wins on Twitter, and blogging a handful of times about my progress. 

But truth be told I never really made it that far.

Programming is unbelievably difficult for me. 
I can spend days and weeks trying to understand a language and how to use it for a given project, and nothing ever really seems to stick. 
I have some theories on why that is, all centered around how we teach programming for data science and machine learning and how we expect learners to learn. 

All of that said, I've still harbored an interest in getting my mind around machine learning, and when I was asked if I was interested in **[participating in #SLICED](https://www.notion.so/SLICED-Show-c7bd26356e3a42279e2dfbafb0480073)**, I didn't hesitate to say yes.

## #SLICED as a forcing function

Forcing functions are events or deadlines that require you to produce some kind of result within a given time frame.
For example, to participate in #SLICED in any meaningful capacity, I knew I had approximately six weeks to learn enough machine learning to be able to produce a model.
I've set the expectation for myself that I want to submit a model -- it doesn't have to be the best model, it doesn't have to be a complex, and it doesn't have to be a technically sophisticated model.
As long as I have a submission on the board before time is called, I'll consider myself successful.  

Knowing I had two weeks of vacation at the end of May, I scheduled time every day to dig in to the `{tidymodels}` resources.
And you know what?
It was absolutely confusing for a few days.
Even though the resources are excellent, I was coming in at such a low knowledge level that it was intimidating to come across unfamiliar terminology and having to look something up every three words.
But I also knew that I was going to be on #SLICED regardless of how much or how little machine learning I understood, so I kept at it.

I wish I could tell you that it only took me two weeks to grasp the code, concepts, and theory behind machine learning, but I'm not even close.
But I _do_ have a solid grasp on the fundamentals, and even [managed to place decently](https://www.kaggle.com/c/sliced-s01e01/leaderboard_) when I played along with season 01, episode 01.

All of this is to say that if you want to learn something and you find yourself constantly starting over, seek out a forcing function that's intense enough to motivate you to cultivate the discipline to get your learning done.
It really is about showing up every day and doing the work.
It's the only way any of us improves.


### `{tidymodels}` resources

* **[Get Started with `{tidymodels}`](https://www.tidymodels.org/start/)**, a series of five articles that introduce you to all the major components of building models with the [tidymodels} framework.
* **[Julia Silge's blog](https://juliasilge.com/blog/)** is an excellent resource. Every week Julia uses the [#TidyTuesday](https://github.com/rfordatascience/tidytuesday) dataset to create a `{tidymodels}` project that she breaks down in both a blog post as well as a screencast.
* **[Learn with `{tidymodels}`](https://www.tidymodels.org/learn/)**, a collection of worked examples that cover specific topics in modeling.
**[`{tidymodels}` package documentation](https://www.tidymodels.org/packages/)** provides links to documentation for each of the packages within the {tidymodels} framework.
* **[Tidy Modeling with R](https://www.tmwr.org/)**, an open-source book that is currently being written by the {tidymodels} team.

_Photo by <a href="https://unsplash.com/@shotgram?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">SHOT</a> on <a href="https://unsplash.com/s/photos/butcher-knife?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>_
