---
title: But do you sleep?
author: Jesse Mostipak
date: '2021-06-05'
slug: []
subtitle: 'lol nope.'
summary: "A reflection on rest, productivity, and finding peace in the absence perfection."
categories:
  - reflection
tags:
  - joy
  - learnML
  - streaming
  - content creation
---
## Busy by choice

You may have noticed that over the last few weeks I've gone from an occasional blog writer to: 

* **[Streaming data visualization, machine learning, and animation content](https://www.twitch.tv/kierisi)** on Twitch
* **[Putting up YouTube content](https://www.youtube.com/user/jmaegan81)** at least once a week
* **[Signing up for #SLICED](https://www.notion.so/SLICED-Show-c7bd26356e3a42279e2dfbafb0480073)** as a forcing function for learning machine learning using the `{tidymodels}` framework
* Dipping my toes back into **[posting on Kaggle](https://www.kaggle.com/jessemostipak/getting-started-with-tidymodels-and-xgboost)**
* **[Tweeting](http://twitter.com/kierisi)** a potentially excessive amount
* **Enrolling in the [RISD animation program](https://cereg.risd.edu/public/category/courseCategoryCertificateProfile.do?method=load&certificateId=2064527)** 
* **Overhauling this blog** _and actually starting to use it_

in the span of about two and a half weeks.

And after a night of streaming followed by posting two videos and a blog post 12 hours later, someone kindly asked "But do you sleep?"

On the one hand, no. 
I'm dealing with a massive bout of insomnia and it kind of sucks. 

But on the other I feel like I've finally tapped into something and I literally cannot stop creating content.

## Sometimes it takes awhile to get to failure

I worked on a project recently that I spent far too much time on. 
What should have taken me two weeks took me several months, and by the time the project launched it had had morphed into something that was no longer recognizable as my own but yet at the same time was something I felt was deeply precious and amazing. 

And once it launched it flopped, hurting my ego in new and surprising ways. 

I don't think of myself as a particularly sensitive person, but for reasons I can't explain I couldn't let go of this.
It was _bothering me_ to levels that were out of the ordinary.
I had spent months -- _MONTHS!_ -- on this project only to shepherd it into the world not only to find myself disappointed in what I had created, but also unnerved by the levels to which this project had flopped. 

My friends were kind and supportive the first few times I brought it up before it became clear that this was a topic that they were tired of dissecting. 
And in the tough love kind of honesty that only those who can empathize with you can use, someone suggested that I start producing _more_. 

## Produce more? HOW WILL I FIND THE TIME?!?!

I resisted the idea that the solution to my bruised ego was to not only get back out there and continue creating, but to create _so much more_ that by the time critiques rolled around on a given project I would already be six projects ahead and no longer fazed by the success or failure of something in my rear view mirror.

It sounded ridiculous to me because I couldn't imagine being in a state where I wasn't deeply invested in the success or failure of something I had created.

What's more, if I was going to start developing content at a rapid pace this would mean I couldn't spend the time and effort on each individual project that I traditionally think of as necessary.
Instead it meant focusing on hitting some bare minimum level of quality, releasing the content, and moving on to the next thing.

## Nothing is precious anymore

I'm not entirely sure what the turning point moment was for me. 
It might have been after [my first #TidyTuesday Unfiltered](https://www.twitch.tv/videos/1034279289) stream, which ended at around 10PM my time, where I found myself thinking "oh gosh I've publicly commit to having a blog post and video up by tomorrow this cannot be a precious endeavor -- how can I be efficient?"

Because while I love all of you, I also love attempting to sleep before 11PM.  

And so I did it -- I knocked out a blog post and video in rapid succession.
And while I knew that I was leaving a lot of creativity and perfectionism on the cutting room floor, the feeling of satisfaction at having everything done and queued up after an hour's worth of work displaced any doubts I had about the approach.

This doesn't mean my work is haphazard or sloppy, because I still have a quality level that I'm striving for. 
I want my work to be something that I stand behind, but I also want to get it out into the world so that I can get feedback in order to iterate, grow, and improve.  

## Perpetual Flow State

One of the most surprising benefits of this approach has been that I've spent the last two weeks able to readily tap into a [flow state](https://en.wikipedia.org/wiki/Flow_(psychology)) whenever I need to. 

And I think part of this is because I'm more focused on getting things done than I am on making them perfect. 
What's more, I'm working across so many platforms that my project idea list is constantly overflowing. 
So it's suddenly easy to check the list and pick out something that I _feel_ like working on, and start executing. 


_Photo by <a href="https://unsplash.com/@at8eqeq3?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Dmitry Grigoriev</a> on <a href="https://unsplash.com/s/photos/bee?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>_
