---
title: 'That’s so meta: deconstructing my Data Science Dallas talk'
author: Jesse M
date: '2018-02-14'
slug: that-s-so-meta-deconstructing-my-data-science-dallas-talk
categories:
  - data science
  - education
  - R
  - teaching
  - presenting
  - public speaking
tags:
  - data science
  - education
  - R
  - teaching
  - presenting
  - public speaking
---
## Introduction
I want to start by making it unequivocally clear that I absolutely love teaching, and by extension, public speaking. While some people might break out in a cold sweat at the very thought of standing in front of others and speaking, I get to a point where I can barely contain my excitement. Teaching consistently puts me in a [flow state](https://en.wikipedia.org/wiki/Flow_(psychology)) more so than any other activity, although curriculum design is a close second. _FYI: the irony of being a former public school teacher who just referenced a Wikipedia article is not lost on me._  

## What's covered in this post:
1. Strategy involved in developing the talk
2. Slide design using annotated slides
3. Teaching principles incorporated into the talk  

***

## Strategy

With 30 minutes scheduled to talk at the [Data Science Dallas IDEAS conference](https://www.ideassn.org/dallas-2018/), my goal was to come up with a 20 minute talk that dedicated 10 - 12 minutes to an interactive activity. This approach would leave me with approximately 8 minutes to speak, meaning that I had time to convey no more than two _related_ ideas in an accessible manner. While I thought I was going to talk about R, I decided that it would be best to back up and approach the talk from a (largely) language-agnostic perspective.  

In the weeks leading up to this talk I would write down ideas as they came to me, and then re-work them multiple times into various outlines - discarding ideas and activities that wouldn't work while refining ideas and activities that showed potential. I eventually ended up with the following list:  

1. Backwards planning
2. Project-based learning
3. Collaborative learning
4. Cooperative learning
5. Evaluate assumptions

A list of five items is better than a list of 30, but still too long for eight minutes of speaking. I was also acutely aware of the fact that I needed to translate educational jargon into more broadly understood terms. And so about a week before slides were due I narrowed my focus down to **creating a learning path** (drawn from backwards planning and evaluating assumptions) and **finding your community** (a combination of project-based, collaborative, and cooperative learning).  

I created my initial deck, then left it for 48 hours. By coming back with a fresh perspective I was able to ruthlessly cut anything that didn't relate to my two main ideas. Ruthlessness is essential - just because I sank eight hours into creating custom graphics for the talk didn't mean that these graphics were relevant, useful, or meaningful.  

***

## Slide design  

### Vestiges of teaching
I will forever and always technology-proof my talks. For me to be comfortable and confident, I know that I need to be able to give my talk - **without a loss of impact** - regardless of whether or not the technology in the room is working. In the worst case scenario it was going to be just me and the audience. If the fates were a bit more on my side, the talk would consist of me, the audience, a whiteboard, and working Expo markers. Being able to use slides is nothing but a bonus.  

### Your slides are not your talk

I'm a firm believer that slides need to support the talk, but not _be_ the talk. Because my slides are published online, I have a personal responsibility to create inherent value for every audience member who is present and engaged during the talk.    

I also insist on moving around the room while I'm speaking. With slides, I need to assume that there is no remote slide advancer and so slides need to stand on their own for several minutes as I'm circulating, in order to avoid running back up to the podium every 20 seconds.

With this philosophy in mind, I tend to design slides with very little text on them, ensure that they are accessible to a broad audience, and be branded in such a way that individuals can "find" me via Twitter.  

### So let's see these slides already!

In each of the images you'll see the slide, and on the right hand side there will be text that touches on at least one of the following topics:  

1. Purpose
2. Design principles/teaching practices
3. Key words/points
4. Transition
5. Questions to ask the audience  

#### Slide 1: 

***

## Teaching principles
### Wiggins & McTighe: Understanding by Design
## Lemov: Teach Like a Champion 2.0  

***

## Conclusion
Incorporating design principles and best practices from K-12 education can dramatically improve your presentation. As someone who enjoys both doing these things and helping others do these things, please don't hesitate to reach out to me on [Twitter](https://twitter.com/kierisi)!