---
title: 'R4DS May Challenge: sign up for office hours!'
author: Jesse Mostipak
date: '2018-05-05'
slug: r4ds-may-challenge-sign-up-for-office-hours
categories: []
tags:
  - challenge
  - learning
  - R4DS
  - R
---

# Introduction
May is here and it's time to get back to our roots by revisiting the [R for Data Science text](http://r4ds.had.co.nz/) as well as introduce materials to help you - _yes you_ - get comfortable with [GitHub](https://github.com/).

Sure, we could do something similar to the first iteration of our online learning community and say we're going to cover a specified amount of material each week, but instead we're going to try something new!

# Welcome to office hours!
This month we've had five _amazing_ volunteers donate their time to answer your questions about GitHub and/or data transformation.  

The GitHub resource we'll be using is [Jenny Bryan's](https://twitter.com/JennyBryan) [Happy Git With R](http://happygitwithr.com/), and the data transformation resource we'll be using is [Chapter 5: Data Transformation](http://r4ds.had.co.nz/transform.html) from the __R for Data Science__ text.

# How to participate
If you would like to attend office hours, please sign up using the link posted in our R4DS online learning community Slack group. If you're not yet a member, you can read more about the group and sign up [here](https://www.jessemaegan.com/post/r4ds-the-next-iteration/).  

By signing up for office hours, you are making a commitment to show up during the office hours session. Please be respectful of our mentor volunteers and, well, show up!

You do not have to prepare anything for office hours, and can show up and use the time to start working through the material, knowing that a mentor will be available to answer questions as they arise. However it may be helpful to have at least read through the material ahead of time so that you have an idea of where you might get stuck.

These office hours are a fantastic opportunity to really dive deep into an R for data science project while also getting to know some of our community members, and we can't wait to see you there!
