---
title: Data Science Twitch Streamers Round Up
author: Jesse Mostipak
date: '2021-05-28'
slug: []
categories:
  - Content Creation
  - community
  - data science
  - online learning
  - learnML
tags: []
subtitle: "I can't believe this site is free"
excerpt: ''
images: ~
series: ~
layout: single
---
## Did you know?
There's an entire world of absolutely free live-streamed data science content 
available to you almost 24//7 at [twitch.tv](www.twitch.tv)? 
Me neither. 

I first learned about Twitch when it was still [Justin.tv](https://en.wikipedia.org/wiki/Justin.tv), 
a time that feels like forever ago but also lines up with my entry into data science. 
My first data science job was at an esports startup that was working hard to become a media company (we had a studio and everything!) and I spent a lot of time immersed in streams and following the journeys of different players in order to better design statistical models and infographics to tell their stories.  

Fast forward seven years and I'm now livestreaming video games while talking about data science [on my own Twitch channel](twitch.tv/kierisi). Life is funny like that.  

## The streaming data science community
But I'm not the only one streaming data science content on Twitch!  
Although Twitch has yet to create a programming or data science or machine learning category (I'm not bitter *cough* pools, hot tubs, and beaches *cough*), you can find most of us under the [Science & Technology tag](https://www.twitch.tv/directory/game/Science%20%26%20Technology).  

I'll keep updating this list, but as of right now, here are some data science streamers you should check out, follow, and engage with!   


### mcmullarkey 
**[Dr. Michael Mullarkey](https://www.twitch.tv/mcmullarkey)** streams approximately twice a week, with one stream focused  on leveling up your data science game (hang out, discuss, some live coding), and another stream called "Data Distillery Dash" where they take data they've never seen before, solve a prediction problem in #rstats, & write a distill blog post in 2 hrs or less.


### moriah_streamR
**[Moriah Taylor](https://www.twitch.tv/mcmullarkey)** streams once a week, Thursdays from 6:30-9:30pm EST, and focuses on coding in R. 
Usually she's doing #TidyTuesday, but sometimes talks about other data techniques and general best practices regarding data.  


### nickwan_datasci
**[Nick Wan](https://www.twitch.tv/nickwan_datasci)** streams Monday through Thursday, and not only covers data science, but also manages SLICED with co-host Meg Risdal, which is airing on Tuesdays this summer!

### rctatman
**[Rachael Tatman](https://www.twitch.tv/rctatman/)** streams multiple times a week, with the following schedule (all times Pacific):  

* 4:30 PM Tuesdays, machine learning and natural language processing
* 9:00 AM Wednesdays, Rasa office hours
* 9:00 AM Thursdays, Rasa reading group
* 9:00 AM Fridays, Rasa livecoding

### rpodcast
**[Eric](https://www.twitch.tv/rpodcast)** has a whole host of content, and streams [The Shiny Dev Series](https://twitter.com/shinydevseries) and R development work on a bi-weekly basis.


### TanHo_
**[Tan](https://www.twitch.tv/tanho_)** streams Shiny apps and package development on Saturday evenings, and research (aka data science) on Sunday afternoons.

