---
title: Join the “R for Data Science” online learning community
author: Jesse Mostipak
date: '2017-08-20'
slug: join-the-r-for-data-science-online-learning-community
categories:
  - R
  - R4DS
  - data science
  - education
  - online learning
  - community
tags:
  - R
  - R4DS
  - data science
  - education
  - online learning
  - community
---

### Introduction  

Every day I talk to individuals who are working in one field, but are interested in learning more about how and where to get started in data analysis either as a hobby, or as part of a broader career transition. While there are a myriad of options out there - from online bootcamps to self-guided study through various web platforms and textbooks - it can be daunting to start something like this on your own.  

But you don’t have to learn data analysis or R on your own! Instead, join this (new and definitely a bit of an experiment) online learning community, where you’ll have ongoing discussions with a group of people working on the same goals as you, knowing that no question is a stupid question, and that everyone involved supports your intentions to learn both R and data analysis!  

### Purpose  
The goal of this online community is to provide a friendly and supportive online space for you to work with likeminded people just getting started in data analysis by reading “R for Data Science”, a free and publicly available book written by Garrett Grolemund and Hadley Wickham.  

By the end of the text, all of us will have deepened our knowledge of both R and data analysis, as well as created at least one data analysis project that we can each use in our respective portfolios.  

### Format and pace  
We’ll communicate regularly through Slack, where everyone is free to ask questions, share code, and assist one another as we work through the “R for Data Science” text.
At this point in time the pacing of the course has not been fully established, however it will be reflective of the size and scope of the community. For example, if a large portion of participants are brand new to both R and data analysis, the curriculum will be set up to move a bit slower than if the majority of participants have dabbled in both R and data analysis.  

It is my intention to have the curriculum posted publicly by 9/1/2017, and ensure that the group wraps up before the winter holidays.  

### Roles
There are two main roles within this online community - that of a learner, and that of a mentor. While we are all learners in one capacity or another, for the purposes of this community, the distinction between the two is as follows:  

#### Learner
* You have little to no experience with R
* You have little to no data analysis experience
* You have regular access to both a computer and internet connection
* You are comfortable installing software on your computer
* You can commit a minimum of 3–5 hours a week to spend reading the text, completing the exercises, and discussing the week’s readings and exercises via Slack
* You will be an active participant on Slack, logging in at least once a week to interact with others regarding the exercises and/or reading
* You will be responsible for your own learning
* You will adhere to the code of conduct

#### Mentor
* You enjoy contributing to the creation of a positive online learning community
* You don’t get frustrated when someone asks (for the 100th time) what a factor is - in fact, you’re excited to come up with multiple methods to help ensure that someone is learning and mastering the material
* You have 1–2 hours a week that you can spend answering questions via Slack, and working with learners to help them expand their skillset
* You will adhere to a code of conduct

### Important dates
* 8/31/2017: Last day to sign up for the online learning community
* 9/1/2017: Slack invitations go out
* 9/1–9/7: Introductions & Setting Up Your Work Environment
  + Introduce yourself and get to know others in the group
  + Read and discuss the Welcome as well as sections 1, 6, and 8 in the text
  + Install necessary software on your machine.

#### Update
This version of the R for Data Science online learning community is now closed. You can learn more about the next iteration [here](https://www.jessemaegan.com/post/r4ds-the-next-iteration/).